easy_words = [
    "apple", "banana", "orange", "grape", "pear", "plum", "melon", "berry",
    "fig", "kiwi", "guava", "carrot", "potato", "tomato", "onion", "garlic",
    "pepper", "corn", "camel", "baboon", "tiger", "lion", "zebra", "monkey",
    "rabbit", "whale", "shark", "eagle", "parrot", "owl", "crow", "ant",
    "bee", "friend", "family", "mother", "father", "doctor", "nurse",
    "farmer", "chef", "pilot", "driver", "school", "teacher", "student",
    "music", "guitar", "piano", "camera", "picture", "beach", "river",
    "ocean", "island", "forest", "bridge", "castle", "cloud", "storm",
    "breeze", "dream", "able", "about", "above", "actor", "adult", "after", 
    "again", "agent", "agree", "ahead", "alarm", "album", "alive", "allow", 
    "alone", "along", "angel", "anger", "apple", "april", "arena", "argue", 
    "arrow", "aside", "asset", "audio", "award", "aware", "bacon", "badge",
    "baker", "basic", "beach", "beard", "beast", "begin", "bench", "berry",
    "birth", "black", "blade", "blame", "blank", "blast", "bleed", "blend",
    "bless", "blind", "block", "blood", "bloom", "board", "boast", "bonus",
    "book", "boost", "booth", "bound", "brain", "brake", "brand", "brave",
    "bread", "break", "brick", "brief", "bring", "broad", "brown", "brush",
    "buddy", "build", "bunch", "burst", "cabin", "cable", "camel", "candy",
    "canoe", "carry", "catch", "cause", "chain", "chair", "chalk", "charm",
    "chart", "cheap", "check", "cheek", "cheer", "chess", "chief", "child",
    "choir", "claim", "class", "clean", "arise", "array",   "clear", "clerk", 
    "coach", "coast", "color", "count", "court", "cover", "craft", "crane",
    "crash", "cream", "creek", "cross", "crowd", "crown", "curve", "cycle",
    "daily", "dance", "dairy", "death", "delay", "devil", "diary", "dinner",
    "dirty", "doubt", "dozen", "draft", "drama", "dream", "dress", "drink",
    "drive", "eager", "eagle", "early", "earth", "eight", "elbow", "elder",
    "elect", "empty", "enemy", "enjoy", "enter", "entry", "equal", "error",
    "event", "every", "exact", "exist", "extra", "faith", "false", "fancy",
    "fault", "favor", "feast", "fence", "fever", "fiber", "field", "fight",
    "final", "first", "flame", "flash", "fleet", "flesh", "float", "floor",
    "flour", "focus", "force", "forth", "frame", "fresh", "front", "frost",
    "fruit", "funny", "giant", "glass", "globe", "glory", "grace", "grade",
    "grain", "grand", "grant", "grass", "click", "climb", "clock", "close", 
    "cloth", "cloud", "grape", "graph", "grasp", "great", "green", "greet", 
    "grill", "group", "guard", "guess", "guest", "guide", "habit", "happy", 
    "heavy", "honey", "horse", "hotel", "house", "human", "humor", "hurry",
    "ideal", "image", "index", "inner", "input", "issue", "jelly", "jewel",
    "joint", "judge", "juice", "kitty", "knife", "knock", "label", "labor",
    "large", "laser", "laugh", "layer", "learn", "leave", "legal", "lemon",
    "level", "light", "limit", "liver", "local", "lodge", "lucky", "lunch",
    "magic", "major", "maker", "maple", "march", "match", "metal", "meter",
    "might", "minor", "model", "money", "month", "moral", "motor", "mouse",
    "mouth", "movie", "music", "naked", "narrow", "nation", "native", "nature",
    "nearly", "needle", "noble", "normal", "number", "object", "ocean", "office",
    "olive", "open", "order", "organ", "other", "owner", "paint", "panel",
    "paper", "party", "peace", "peach", "harbor", "heart", "pearl", "penny", 
    "phase", "phone", "photo", "piece", "pilot", "pizza", "place", "plain", 
    "plane", "plant", "plate", "point", "pound", "power", "press", "price", 
    "pride", "prime", "print", "prize", "proof", "queen", "quick", "quiet", 
    "radio", "raise", "ranch", "range", "rapid", "reach", "ready", "reply", 
    "reset", "rhino", "right", "rival", "river", "robot", "rock", "rough", 
    "round", "route", "royal", "ruler", "rural", "salad", "scale", "scene", 
    "scope", "score", "screen", "search", "season", "secret", "shadow", "shake", 
    "shape", "share", "sharp", "sheep", "sheet", "shelf", "shell", "shirt", 
    "shore", "short", "shout", "sight", "silver", "simple", "sister", "skill", 
    "sleep", "slice", "smile", "smoke", "snake", "solid", "solve", "sound", 
    "space", "spare", "speak", "speed", "spend", "spice", "spoon", "sport", 
    "spring", "square", "stage", "stand", "start", "steam", "steel", "stick", 
    "stone", "store", "storm", "story", "straw", "street", "strong", "studio",
    "sugar", "summer", "sunny", "super", "supply", "sweet", "table", "taste", 
    "teach", "thank", "theme", "there", "thick", "thing", "think", "third", 
    "throw", "thumb", "tiger", "title", "today", "topic", "total", "touch", 
    "tower", "track", "trade", "train", "travel", "treat", "trend", "trial", 
    "tribe", "truck", "truly", "trust", "truth", "uncle", "under", "union", 
    "unity", "upper", "upset", "urban", "usage", "usual", "value", "video", 
    "visit", "voice", "voter", "wagon", "waist", "water", "wealth", "weather", 
    "wedding", "wheel", "where", "which", "while", "white", "whole", "woman", 
    "wonder", "wooden", "world", "worry", "worth", "writer", "yellow", "young", 
    "zebra", "zipper", "anchor", "animal", "answer", "balloon", "battery", "blanket", 
    "captain", "country", "diamond", "evening", "factory", "garden", "holiday", 
    "kitchen", "morning", "rainbow", "school", "village", "window", "winter"
]

medium_words = [
    "aardvark", "apricot", "avocado", "papaya", "cabbage", "broccoli",
    "spinach", "lettuce", "celery", "village", "jungle", "desert",
    "valley", "mountain", "canyon", "volcano", "waterfall", "meadow",
    "planet", "galaxy", "comet", "rocket", "satellite", "orbit",
    "dragon", "wizard", "knight", "pirate", "ninja", "robot",
    "alien", "monster", "ghost", "vampire", "zombie", "giant",
    "window", "mirror", "ladder", "hammer", "pencil", "notebook",
    "backpack", "blanket", "pillow", "candle", "lantern", "bottle",
    "basket", "bucket", "helmet", "glasses", "library", "college",
    "science", "history", "grammar", "violin", "trumpet", "drummer",
    "singer", "artist", "drawing", "painting", "statue", "museum",
    "gallery", "theater", "football", "baseball", "cricket", "tennis",
    "soccer", "hockey", "running", "swimming", "cycling", "jumping",
    "skiing", "rowing", "boxing", "golf", "elephant", "giraffe",
    "gorilla", "hamster", "penguin", "dolphin", "turtle", "falcon",
    "sparrow", "peacock", "captain", "soldier", "police",
    "builder", "judge", "sunrise", "sunset", "rainbow", "thunder",
    "shadow", "silence", "whisper", "adventure", "treasure",
    "journey", "mystery", "victory", "freedom", "happiness",
    "kindness", "courage",     "ability", "absence", "academy", "account", "achieve", "acoustic", "activity", "adoption",
    "advance", "adventure", "airplane", "alphabet", "amazing", "ancient", "another", "anxiety",
    "apartment", "apology", "apparent", "approach", "aquarium", "argument", "armchair", "arrival",
    "assembly", "athlete", "attitude", "audience", "backpack", "backyard", "balance", "balloon",
    "baseball", "bathroom", "battery", "beautiful", "bedroom", "behavior", "birthday", "blanket",
    "blossom", "bookcase", "boundary", "bracelet", "breakfast", "broccoli", "building", "business",
    "calendar", "campaign", "campsite", "candle", "captain", "carpenter", "carriage", "cartoon",
    "cathedral", "celebrate", "cemetery", "champion", "chandelier", "character", "children", "chocolate",
    "cinnamon", "citizen", "classroom", "clothing", "coastline", "coconut", "collection", "collision",
    "computer", "concert", "condition", "confident", "confusion", "connection", "container", "continent",
    "contract", "corridor", "costume", "cottage", "courtyard", "creature", "criminal", "crossing",
    "cupboard", "curiosity", "customer", "daydream", "decision", "decorate", "delivery", "departure",
    "detective", "dictionary", "dinosaur", "direction",     "discovery", "distance", "document", "dolphin", "dominate", "doorway", "download",
    "dragon", "drawing", "dreaming", "drummer", "electric", "elephant", "elevator",
    "emotion", "employee", "engineer", "entrance", "envelope", "episode", "equipment",
    "escape", "evening", "exchange", "excited", "exercise", "explorer", "factory",
    "fairyland", "family", "fantasy", "farmer", "favorite", "festival", "fiction",
    "firefighter", "fireplace", "fishpond", "flamingo", "flowerpot", "football",
    "forest", "fortune", "forward", "freedom", "friendly", "furniture", "galaxy",
    "gallery", "garbage", "garden", "gateway", "general", "gentleman", "giant",
    "glacier", "glasses", "goodness", "government", "grammar", "grandfather",
    "grasshopper", "greenhouse", "grocery", "guitar", "hamburger", "happiness",
    "hardware", "headache", "headline", "healthy", "helicopter", "history",
    "horizon", "hospital", "household", "hundred", "hurricane", "iceberg",
    "imagination", "important", "industry", "information", "insect", "instrument",
    "internet", "island", "jewelry", "journey", "jungle", "keyboard", "kingdom",
    "kitchen", "language", "lantern", "laughter", "leader", "learning", "library",
    "lightning", "location",     "machine", "magazine", "manager", "market", "marriage", "material", "medicine",
    "memory", "message", "metallic", "midnight", "million", "mineral", "mission",
    "monster", "motorcycle", "mountain", "movement", "musical", "mystery",
    "national", "natural", "neighbor", "newspaper", "nightmare", "northern",
    "notebook", "novelty", "number", "nurse", "observation", "ocean", "officer",
    "operation", "opinion", "orchard", "organization", "original", "outdoor",
    "package", "painting", "painter", "palace", "paragraph", "passenger",
    "password", "peacock", "penguin", "perfect", "performance", "permission",
    "personal", "photograph", "pioneer", "planet", "plastic", "platform",
    "pleasant", "pocket", "poetry", "police", "popular", "position", "possible",
    "pottery", "practice", "precious", "prepare", "present", "president",
    "problem", "process", "produce", "professor", "project", "promise",
    "protect", "purple", "puzzle", "quality", "quarter", "question", "quickly",
    "rainbow", "railroad", "reaction", "reading", "reality", "reason",
    "receipt", "record", "recycle", "reflect", "regular", "relaxing",
    "remember", "restaurant", "result", "rocket", "running", "science",
    "scorpion", "seasonal",     "secretary", "security", "sentence", "separate", "service", "shadow",
    "shelter", "shoulder", "silence", "similar", "skating", "skeleton",
    "society", "soldier", "solution", "someone", "southern", "speaker",
    "special", "station", "student", "sunrise", "sunset", "support",
    "surprise", "swimming", "symbol", "teacher", "teaching", "technology",
    "telephone", "telescope", "temperature", "terrible", "theater",
    "thought", "thunder", "ticket", "together", "tomorrow", "toolbox",
    "tourist", "traffic", "treasure", "triangle", "tropical", "trumpet",
    "turtle", "typical", "umbrella", "unicorn", "universe", "vacation",
    "valley", "vegetable", "vehicle", "version", "victory", "volcano",
    "volleyball", "voyage", "warning", "waterfall", "weakness", "website",
    "wedding", "weekend", "welcome", "whistle", "wildlife", "window",
    "winter", "wizard", "woodland", "workshop", "writer", "yesterday",
    "youngster", "zookeeper", "aircraft", "airport", "alligator",
    "ambition", "ancestor", "anniversary", "apartment", "appearance",
    "astronaut", "attention", "attraction", "authority", "background",
    "basketball", "battlefield", "bedtime", "beginning", "blueberry",
    "breakthrough", "calculator", "celebration",     "championship", "chemistry", "childhood", "classmate", "climate",
    "climbing", "clockwork", "clover", "coastline", "colorful",
    "community", "companion", "competition", "complete", "condition",
    "conference", "connection", "construction", "conversation", "courage",
    "creativity", "criminal", "crossword", "customer", "dangerous",
    "darkness", "database", "daughter", "daylight", "decision", "deepwater",
    "delivery", "department", "desert", "designer", "destination",
    "developer", "diamond", "difference", "disaster", "distance",
    "documentary", "earthquake", "education", "electricity", "emergency",
    "emperor", "energy", "environment", "equipment", "especially",
    "experience", "explosion", "expression", "extraordinary", "fairytale",
    "farmhouse", "feather", "fictional", "firework", "flashlight",
    "floating", "footballer", "friendship", "frostbite", "fruitcake",
    "galaxy", "generation", "geography", "government", "grandmother",
    "grassland", "greenland", "guardian", "handwriting", "headphone",
    "heartbeat", "hometown", "honeybee", "horseback", "houseplant",
    "icecream", "identity", "impossible", "improvement", "incredible",
    "independent", "inventor", "jellyfish", "journalist", "landscape",
    "leadership", "lighthouse", "limestone", "literature", "magician",
    "masterpiece", "mechanic", "microscope", "midfielder", "moonlight",
    "motorboat", "mushroom", "navigation", "newspaper"
]

hard_words = [
    "coconut", "lemon", "lime", "griffin", "unicorn", "mermaid",
    "phoenix", "asteroid", "meteor", "octopus", "squirrel",
    "flamingo", "butterfly", "spider", "beetle", "dragonfly",
    "grasshopper", "ladybug", "firefighter", "engineer",
    "carpenter", "lightning", "snowflake", "raindrop",
    "neighbor", "brother", "sister", "cousin", "uncle", "aunt",
    "echo", "volleyball",     "abbreviation", "acceleration", "accommodation", "achievement", "acknowledge",
    "agriculture", "allegiance", "amphibian", "architecture", "artificial",
    "astronomical", "atmosphere", "authentication", "availability", "background",
    "biodiversity", "biography", "blueprint", "breakthrough", "calculation",
    "camouflage", "catastrophe", "celebration", "civilization", "classification",
    "combination", "communication", "complicated", "composition", "concentration",
    "configuration", "consequence", "conservation", "constitution", "contamination",
    "conversation", "cooperation", "coordination", "corporation", "creativity",
    "crystallize", "declaration", "demonstration", "description", "destination",
    "determination", "development", "disappointment", "discovery", "disruption",
    "documentary", "dragonfly", "earthquake", "ecosystem", "electrician",
    "encyclopedia", "engineering", "entertainment", "environment", "equilibrium",
    "evaporation", "examination", "explanation", "exploration", "extraordinary",
    "fascinating", "firefighter", "fluorescent", "foundation", "freelancer",
    "generation", "geological", "governmental", "grandfather", "grasshopper",
    "gravitational", "handicraft", "helicopter", "hemisphere", "hypothesis",
    "imagination", "infrastructure", "intelligence", "investigation", "journalism",
    "kaleidoscope", "laboratory", "landmark", "leadership", "magnificent",
    "maintenance", "masterpiece", "mathematical", "mechanical", "meteorology",
    "microphone", "microscope", "migration", "mysterious", "navigation",
    "neighborhood", "observation", "opportunity", "organization", "photography",
    "accomplishment", "adaptation", "administrator", "adventurous",
    "aggressive", "alternative", "announcement", "anticipation",
    "application", "appreciation", "archaeology", "arrangement",
    "association", "astonishing", "astronautical", "authorization",
    "beautifully", "beneficial", "biological", "calculator",
    "capability", "catastrophic", "celebrity", "championship",
    "characteristic", "chemistry", "circumstance", "clarification",
    "classification", "collection", "commander", "commercial",
    "communication", "companion", "competition", "comprehensive",
    "conclusion", "confirmation", "conservation", "consideration",
    "construction", "consultation", "continuation", "contribution",
    "controversy", "convenience", "coordinator", "correlation",
    "counterattack", "craftsmanship", "creature", "cryptocurrency",
    "curiosity", "declaration", "decoration", "deforestation",
    "deliberation", "demonstration", "description", "determination",
    "developmental", "dictionary", "differentiation", "disagreement",
    "disappearance", "discrimination", "discovery", "distribution",
    "dramatically", "earthquake", "electricity", "embarrassment",
    "emergency", "encouragement", "encyclopedic", "endangered",
    "enthusiasm", "entrepreneur", "environmental", "equivalent",
    "establishment", "evaluation", "exaggeration", "examination",
    "exceptional", "experiment", "explanation", "extinction",
    "familiarity", "fantastical", "fermentation", "fluorescence",
    "foundation", "friendliness", "fundamental", "geography",
    "grandmother", "gravitational", "greenhouse", "hallucination",
    "headquarters", "historical", "improvement", "independence"
    "abundance", "acceleration", "acquaintance", "administration",
    "advertisement", "agricultural", "algorithm", "ambassador",
    "analysis", "anniversary", "anonymous", "anticipation",
    "appreciation", "approximation", "archipelago", "arrangement",
    "artificiality", "availability", "beneficiary", "bibliography",
    "biotechnology", "breakthrough", "calibration", "catastrophe",
    "celebrity", "civilization", "classification", "collaboration",
    "combustion", "commemoration", "commercialization", "complication",
    "comprehension", "concentration", "confidential", "configuration",
    "congratulation", "conservationist", "considerable", "constellation",
    "constitutional", "contamination", "contradiction", "controversial",
    "conversation", "coordinator", "correspondence", "counterclockwise",
    "craftsmanship", "crystallization", "decomposition", "dedication",
    "deficiency", "demonstration", "dependency", "deprivation",
    "destination", "determination", "devastation", "differential",
    "digitalization", "disadvantage", "disappearance", "disappointment",
    "discovery", "distinction", "distribution", "documentation",
    "dramatic", "earthquake", "electromagnetic", "electronics",
    "embroidery", "encyclopedia", "endangered", "entrepreneurship",
    "environmentalist", "equation", "establishment", "evolutionary",
    "exaggeration", "exceptional", "exclamation", "exploration",
    "extensive", "extraterrestrial", "fabrication", "fascination",
    "feasibility", "fertilization", "firefighter", "fluctuation",
    "foundation", "fundamental", "genealogy", "generation",
    "geometric", "glamorous", "governmental", "gravitational",
    "handkerchief", "hypothesis", "illustration", "imagination",
    "identification", "illumination", "illustration", "immediately",
    "implementation", "improvement", "inaccessible", "incredible",
    "accumulation", "acknowledgement", "acquisition", "adaptability",
    "administrative", "aerodynamic", "agriculturist", "allegorical",
    "amplification", "anthropology", "archaeologist", "astronomical",
    "authentication", "autobiography", "breathtaking", "bureaucracy",
    "camouflage", "characterization", "circumference", "civilization",
    "collaboration", "commencement", "communication", "compassionate",
    "comprehensively", "congratulations", "conservation", "contemporary",
    "contradictory", "cryptography", "decentralization", "decisionmaking",
    "deconstruction", "deforestation", "demonstrative", "departmental",
    "destruction", "determining", "developmental", "disadvantageous",
    "discrimination", "displacement", "documentation", "domestication",
    "ecological", "economical", "electromagnetism", "encyclopedic",
    "enlightenment", "entrepreneurial", "environmentalist", "equilibrium",
    "establishment", "exceptionally", "experimentation", "extravagant",
    "familiarization", "fantastically", "fermentation", "fluorescent",
    "formalization", "fundamentally", "genealogical", "geographical",
    "globalization", "governmental", "hallucination", "handicraft",
    "hierarchical", "hypothetical", "identification", "imagination",
    "industrialization", "ineffectiveness", "influential", "infrastructure",
    "interconnection", "interpretation", "inventiveness", "investigator",
    "irrelevance", "knowledgeable", "manufacturing", "microorganism",
    "misinterpretation", "multicultural", "nanotechnology", "naturalistic",
    "neighborhood", "nontraditional", "observation", "oceanography",
    "pharmaceutical", "photographic", "physiological", "predestination",
    "professional", "psychological", "reconstruction", "representation",
    "responsibility", "technological", "telecommunication", "transformation"
]